name       : puddletag
version    : 2.2.0
release    : 4
source     :
    - https://github.com/puddletag/puddletag/archive/refs/tags/2.2.0.tar.gz : fc26a9fcd842e3cd4b97ac83b9fdbd270d73f2a90285e47135e2719dcacc986a
homepage   : https://docs.puddletag.net/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Powerful, simple, audio tag editor for GNU/Linux
description: |
    puddletag is an audio tag editor (primarily created) for GNU/Linux similar to the Windows program, Mp3tag. Unlike most taggers for GNU/Linux, it uses a spreadsheet-like layout so that all the tags you want to edit by hand are visible and easily editable.
builddeps  :
    - python-build
    - python-installer
    - python-scikit-build
rundeps    :
    - mutagen
    - pyparsing
    - python-configobj
    - python-pyacoustid
    - python-levenshtein
    - python-lxml
    - python3-qt5
setup      : |
    %patch -p1 < $pkgfiles/puddletag-2.2.0-req.patch # patch from Fedora
build      : |
    %python3_setup
install    : |
    %python3_install
