name       : puddletag
version    : 1.2.0
release    : 1
source     :
    - https://github.com/keithgg/puddletag/releases/download/v1.2.0/puddletag-1.2.0.tar.gz : 12dab2c3dbbb1ee63ea26f17af969ebdbcbf1c9e4265f9d9f6f6d16b227120d5
license    :
	- GPL-2.0
	- GPL-3.0
component  : multimedia.audio
summary    : puddletag is an audio tag editor (primarily created) for GNU/Linux similar to the Windows program, Mp3tag.
description: |
    puddletag is an audio tag editor (primarily created) for GNU/Linux similar to the Windows program, Mp3tag. Unlike most taggers for GNU/Linux, it uses a spreadsheet-like layout so that all the tags you want to edit by hand are visible and easily editable.
builddeps  :
    - pkgconfig(libchromaprint)
rundeps     :
    - mutagen
    - pyparsing
    - python-qt4
build      : |
    %python_setup
install    : |
    %python_install
